feat(wallet/ui): interactive, background signing (#5877)
* build(demo-signing): cosmjs, parcel, ... for keplr/ledger demo

* feat(demo-signing): sign and broadcast WalletAction

without ledger

 - toward keplr/ledger demo: copy SuggestChain.js
 - sign simple msg/doc with keplr/ledger (WIP)
   - ISSUE: started with cosmjs API integration but
     couldn't get it to work without skipping it
 - chore(demo-signing): figured out offlignSigner.signAmino() API
   no longer skipping all the way to keplr.signAmino()
 - feat(demo-signing): sign WALLET_ACTION with keplr, ledger
 - send signed transaction to chain (WIP)
   - can connect to chain and query for sequence
   - aminoTypes seem to work
   - TODO: generate protobuf codec for MsgWalletAction
 - pass connectWithSigner authority explicitly
 - integrate MsgWalletAction proto stub via registry
 - MsgWalletAction.owner is bytes, not string

provide enough gas

avoid:

Error: Broadcasting transaction failed with code 11 (codespace: sdk). Log: out of gas in location: ReadFlat; gasWanted: 250, gasUsed: 1000: out of gas
    at SigningStargateClient.broadcastTx (stargateclient.ts:413:9)
    at async HTMLButtonElement.<anonymous> (keplr-ledger-demo.js:215:16)

* feat(demo-signing): authz grant WalletAction to ephemeral key

 - workaround: cosmjs lacks support for fee-account in MsgExec
 - misc static types

addressed:

Error: Broadcasting transaction failed with code 2 (codespace: sdk). Log: no concrete type registered for type URL /agoric.swingset.MsgWalletAction against interface *authz.Authorization: tx parse error
    at SigningStargateClient.broadcastTx (stargateclient.ts:413:9)
    at async Object.authorizeMessagingKey (keplr-ledger-demo.js:183:18)

basic fee grant to messaging key

example result:

agoric-sdk/packages/cosmic-swingset$ ~/go/bin/agd query tx E0EDE9B200AB0B9FF33DA288BC9E455C228854D76D5AD12C80EA5138C6706D06
...
timestamp: "2022-07-20T03:07:21Z"
tx:
  '@type': /cosmos.tx.v1beta1.Tx
  auth_info:
    fee:
      amount:
      - amount: "0"
        denom: uist
      gas_limit: "100000"
      granter: ""
      payer: ""
    signer_infos:
    - mode_info:
        single:
          mode: SIGN_MODE_DIRECT
      public_key:
        '@type': /cosmos.crypto.secp256k1.PubKey
        key: AggWzZHxF8d7Quy/N9UUGWwU05pIEJKNFGFPpfx01Ika
      sequence: "4"
  body:
    extension_options: []
    memo: ""
    messages:
    - '@type': /cosmos.authz.v1beta1.MsgGrant
      grant:
        authorization:
          '@type': /cosmos.authz.v1beta1.GenericAuthorization
          msg: /agoric.swingset.MsgWalletAction
        expiration: "2022-07-20T07:07:22Z"
      grantee: agoric12ufmm960ynt0svr8c7gwy9he909z34w73fkue8
      granter: agoric1uh4ynz9h3ea9vc80tl30s4ykmcyqwfl0d7zelw
    - '@type': /cosmos.feegrant.v1beta1.MsgGrantAllowance
      allowance:
        '@type': /cosmos.feegrant.v1beta1.BasicAllowance
        expiration: "2022-07-20T07:07:22Z"
        spend_limit:
        - amount: "250000"
          denom: uist
      grantee: agoric12ufmm960ynt0svr8c7gwy9he909z34w73fkue8
      granter: agoric1uh4ynz9h3ea9vc80tl30s4ykmcyqwfl0d7zelw
    non_critical_extension_options: []
    timeout_height: "0"
  signatures:
  - JTO/ouDtWgTB8fO8ngHceQk+AxIup8tWClaKEFCOqiE1N5gC2TEVN2CiKch2tmE6/Pj2NXJH9DoGFEpz5WBB7A==
txhash: E0EDE9B200AB0B9FF33DA288BC9E455C228854D76D5AD12C80EA5138C6706D06

feat(demo-signing): use ephemeral messaging key to do actions (WIP)

struggling to get it to work.

currently gives:

"failed to execute message; message index: 0: authorization not found: unauthorized"

despite:

$ agd query authz grants agoric1uh4ynz9h3ea9vc80tl30s4ykmcyqwfl0d7zelw agoric1prh40kcgtx4uxd870aye5swmqzdrfu4ggp5pfm
grants:
- authorization:
    '@type': /cosmos.authz.v1beta1.GenericAuthorization
    msg: /agoric.swingset.MsgWalletAction
  expiration: "2022-07-20T08:42:41Z"

* feat(demo-signing): query WalletAction grants

* chore(demo-signing): factor out keyManagement.js

* chore(demo-signing): check ledger status: nope

grant fails thusly:

aminotypes.ts:38 Uncaught (in promise) Error: The message type '/cosmos.authz.v1beta1.MsgGrant' cannot be signed using the Amino JSON sign mode because this is not supported by chain.
    at AminoTypes.toAmino (aminotypes.ts:38:13)
    at signingstargateclient.ts:351:56
    at Array.map (<anonymous>)
    at SigningStargateClient.signAmino (signingstargateclient.ts:351:27)
    at async SigningStargateClient.signAndBroadcast (signingstargateclient.ts:295:19)
    at async Object.authorizeLocalKey (keyManagement.js:350:18)

and submit offer thusly:

Uncaught (in promise) Error: Broadcasting transaction failed with code 4 (codespace: sdk). Log: signature verification failed; please verify account number (14), sequence (0) and chain-id (agoric): unauthorized
    at SigningStargateClient.broadcastTx (stargateclient.ts:413:9)
    at async Object.submitSpendAction (keyManagement.js:381:18)

* refactor(wallet/ui): SuggestChain: separate IO from compute

 - allow caller to pass authority explicitly

* build(wallet/ui): devDependencies += @agoric/cosmic-proto

* chore(wallet/ui): use packaged protobuf stubs

* chore(wallet/ui): move keyManagement.js from demo-signing

* build(wallet/ui): cosmjs, keplr dependencies

* fix(wallet/ui): handle local-chain rpcAddr

* feat(wallet/ui): sign offer-like JSON (WIP)

* chore(demo-signing): prune

* refactor(wallet/ui): factor out chainInfo.js

* chore(wallet/ui): clean up logging in keyManagement.js

* refactor(wallet/ui): keyManagement naming, docs

* feat(wallet/ui): support WalletSpendAction

* chore(wallet/ui): sign offer-like JSON (cont.)

 - include interactiveSigner, backgroundSigner in state.keplrConnection
 - punt window.cosmJS, whatever that was
 - use tryKeplrConnect in ChainConnector
 - move ambient authority to the edges: Provider.jsx
 - clean up SuggestChain

* chore(wallet/ui): never mind signing test button

* fixup: freeze->harden

Co-authored-by: Michael FIG <michael+github@fig.org>

* fixup: logging misc

Co-authored-by: Turadg Aleahmad <turadg@agoric.com>
Co-authored-by: Michael FIG <michael+github@fig.org>

* fix(keyManagement): urun->uist

Co-authored-by: Michael FIG <michael+github@fig.org>

* refactor(wallet/ui): rename getBytes -> csprng

* fixup! chore(wallet/ui): sign offer-like JSON (cont.)

* fixup! chore(wallet/ui): sign offer-like JSON (cont.)

* fixup! chore(demo-signing): factor out keyManagement.js

* fixup! refactor(wallet/ui): keyManagement naming, docs

* refactor: .map().filter().map() => .flatMap()

Co-authored-by: Michael FIG <michael+github@fig.org>
Co-authored-by: Turadg Aleahmad <turadg@agoric.com>
Co-authored-by: mergify[bot] <37929162+mergify[bot]@users.noreply.github.com>