build(types): --clean option for package isolation
The postpack of a previous package only cleans up files in that package. Its prepack may build files in other packages that it doesn't clean up.
The remants were causing errors like:
```
> @agoric/governance@0.10.4-dev-5988fad.0 prepack /home/runner/work/agoric-sdk/agoric-sdk/packages/governance
> echo "export {}; " | cat - src/types-ambient.js > src/types.js && tsc --build tsconfig.build.json

error TS5055: Cannot write file '/home/runner/work/agoric-sdk/agoric-sdk/packages/ERTP/exported.d.ts' because it would overwrite input file.
```
(in 'https://github.com/Agoric/agoric-sdk/actions/runs/6346051963/job/17239010386?pr=8410'\)

This makes the build clean up files in the way.